name: Telegram-Bot
version: 0.1.0
main: FurryLoaderMC.TelegramBot.Main
description: FurryLoaderMC - Telegram Bot
author: FurryLoaderMC
api-version: "1.20"
commands:
  telegram:
    description: 通过 Bot 发送 / 回复 消息到 Telegram
    usage: /telegram send | at | reply ...