name: Telegram-Message
version: 1.0.0
main: FurryLoaderMC.TelegramMessage.Main
description: FurryLoaderMC - Telegram Message
author: FurryLoaderMC
api-version: "1.20"
commands:
  telegram:
    description: 通过 Bot 发送 / 回复 消息到 Telegram
    usage: /telegram help | send | at | reply ...
